name: Build jd_wstool

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: jd_wstool
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Makefile
        run: |
          mkdir artifacts
          cd jd_wstool
          make release
          mv *.tar.gz ../artifacts || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upload gzip file to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: 京东全自动退会助手
          files: 'artifacts/**'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}